site_name: CityPortraits
site_description: A project showcasing the architectural heritage of cities through portraits
# site_url: https://github.com/greamarchitects/CityPortraits
site_url: https://greamarchitects.github.io/CityPortraits/
dev_addr: 127.0.0.1:8002
site_url: http://127.0.0.1:8002/greamarchitects/CityPortraits/


theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - search.highlight
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - toc.integrate 

nav:
  - Home:
      - Main: index.md

  - Methodology:
      - Intro: methodology/index.md
      - Contextual Analysis: methodology/contextual_analysis/index.md
      - Spatial Analysis: methodology/spatial_analysis/index.md
      - Data Analysis: methodology/data_analysis/index.md

  - Model:
      - model/index.md

  - Case Studies:
      - case_studies/index.md
      - Tirana: case_studies/Tirana.ipynb
      - Durres: case_studies/Durres.ipynb
      - Berat: case_studies/Berat.ipynb
      - Shkodra: case_studies/Shkodra.ipynb

  - About: 
      - about/index.md

  # - Print Version: 
  #     - print_all.md

extra_css:
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.css
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
  - javascripts/timeline-map.js
  - javascripts/graph.js
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - https://unpkg.com/cytoscape/dist/cytoscape.min.js


extra:
  footer:
    copyright: "© 2026 CityPortraits Team"
    custom: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - tables
  - toc:
      toc_depth: 3
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      show_input: false
      include_source: false

markdown_extensions:
  - pymdownx.snippets:
      base_path:
        - docs
      check_paths: true

      